// Routing metadata only. Providers never acquire game-state authority.
const entry = (id, domain, description, command, source, authority, status,
  { mode = 'READ_ONLY', provider = 'runtime', gap = null,
  preconditions = [], audit = mode === 'STATE_CHANGING',
    production = status === 'ALREADY_UNIFIED' && mode === 'READ_ONLY', browser = false } = {}) => ({
  id, domain, description, command, source, authority, mode, provider,
  browser_required: browser, db_direct: provider === 'DB_READ_ONLY',
  audit_required: audit, production_allowed: production,
  required_preconditions: preconditions,
  output_schema: mode === 'STATE_CHANGING' ? 'developer-action-v1' : 'developer-result-v1',
  current_status: status, reusable: status !== 'NOT_IMPLEMENTED_PRODUCT', gap,
});

export const capabilities = Object.freeze([
  entry('runtime.health', 'runtime', 'Service and listener health', 'runtime health', 'ops/ro-stack/dashboard.mjs:/api/internal/health; .local/ro-stack/state.json', 'canonical runtime', 'ALREADY_UNIFIED'),
  entry('runtime.processes', 'runtime', 'Tracked process IDs and runtime generation', 'runtime processes', '.local/ro-stack/state.json', 'canonical runtime', 'ALREADY_UNIFIED'),
  entry('runtime.identity', 'runtime', 'Live executable identity for tracked PIDs', 'runtime identity', 'ops/ro-stack/dev-console/read-process-identity.ps1', 'Windows process and canonical runtime', 'ALREADY_UNIFIED'),
  entry('runtime.logs', 'runtime', 'Bounded Native or Dashboard log tail', 'runtime logs <login|char|map|dashboard> [--char <id>]', '.local/ro-stack/state.json; .local/ro-stack/dashboard/state.json', 'canonical runtime logs', 'ALREADY_UNIFIED'),
  entry('runtime.single', 'runtime', 'Single runtime guard', 'capabilities runtime', 'ops/ro-stack/runtime-sentinel.ps1', 'runtime sentinel', 'MISSING_DEVELOPER_ENTRYPOINT', { gap: 'GAP_SINGLE_RUNTIME_READ' }),
  entry('runtime.snapshot', 'runtime', 'Controlled runtime snapshot', 'capabilities runtime', 'ops/ro-stack/production-runtime-adapter.mjs', 'runtime adapter', 'MISSING_DEVELOPER_ENTRYPOINT', { mode: 'STATE_CHANGING', gap: 'GAP_RUNTIME_SNAPSHOT', production: false }),
  entry('runtime.lifecycle', 'runtime', 'Controlled start and stop', 'capabilities runtime', 'ops/ro-stack/ro-stack.ps1; ops/ro-stack/dashboard-service.ps1', 'canonical service tools', 'EXISTS_SCRIPT_ONLY', { mode: 'STATE_CHANGING', production: false }),
  entry('player.inspect', 'player', 'Authenticated roster and PA live projection', 'player inspect <charId>', 'ops/ro-stack/dashboard.mjs:listAdminCharacters', 'Dashboard Admin read model', 'ALREADY_UNIFIED', { provider: 'Dashboard', preconditions: ['RO_LOCAL_ADMIN_TOKEN'] }),
  entry('player.fleet', 'player', 'Bounded Admin character roster', 'player fleet', 'ops/ro-stack/dashboard.mjs:listAdminCharacters', 'Dashboard Admin read model', 'ALREADY_UNIFIED', { provider: 'Dashboard', preconditions: ['RO_LOCAL_ADMIN_TOKEN'] }),
  entry('player.quarantine', 'player', 'Quarantined roster census', 'player quarantine', 'ops/ro-stack/dashboard.mjs:listAdminCharacters', 'Dashboard Admin read model', 'ALREADY_UNIFIED', { provider: 'Dashboard', preconditions: ['RO_LOCAL_ADMIN_TOKEN'] }),
  entry('player.recovery', 'player', 'Canonical quarantine recovery', 'action recover-quarantined <charId> --execute', 'ops/ro-stack/developer-admin-action.mjs', 'Dashboard Admin to Native', 'ALREADY_UNIFIED', { mode: 'STATE_CHANGING', provider: 'existing canonical action', production: true, preconditions: ['RO_LOCAL_ADMIN_TOKEN', 'operator approval', 'Production gates'] }),
  entry('player.recovery_preflight', 'player', 'Read-only roster preflight for recovery', 'action recover-quarantined <charId> --preflight', 'ops/ro-stack/developer-admin-action.mjs', 'Dashboard Admin read model', 'ALREADY_UNIFIED', { provider: 'existing canonical action', preconditions: ['RO_LOCAL_ADMIN_TOKEN'] }),
  entry('player.command', 'player', 'Recent Native commands', 'player commands <charId>', 'persistent_agent_command', 'Native command ledger', 'ALREADY_UNIFIED', { provider: 'DB_READ_ONLY' }),
  entry('player.live_inventory', 'player', 'Six-field Native inventory and supply projection', 'player live-inventory <charId>', 'persistent_agent_live_status', 'Native PA live-status read model', 'ALREADY_UNIFIED', { provider: 'DB_READ_ONLY' }),
  entry('player.generation', 'player', 'Resident owner and generation correlation', 'player inspect <charId>', 'persistent_agent_live_status; .local/ro-stack/state.json', 'Native PA and canonical runtime', 'MISSING_DEVELOPER_ENTRYPOINT', { gap: 'GAP_GENERATION_JOIN' }),
  entry('player.collision', 'player', 'Ownership collision and stale generation census', 'capabilities player', 'persistent_agent_state; persistent_agent_live_status', 'Native PA', 'MISSING_DIAGNOSTIC', { gap: 'GAP_FLEET_COLLISION' }),
  entry('events.recent', 'events', 'Recent factual events by character', 'events recent <charId>', 'persistent_life_event', 'Event Ledger', 'ALREADY_UNIFIED', { provider: 'DB_READ_ONLY' }),
  entry('events.cursor', 'events', 'Stable cursor and command or target correlation', 'capabilities events', 'persistent_life_event', 'Event Ledger', 'MISSING_DEVELOPER_ENTRYPOINT', { provider: 'DB_READ_ONLY', gap: 'GAP_EVENT_CORRELATION' }),
  entry('combat.activity', 'combat', 'Last hit kill and loot projection', 'player inspect <charId>', 'ops/ro-stack/dashboard.mjs:readAdminCharacterActivity', 'Event Ledger through Admin read model', 'ALREADY_UNIFIED', { provider: 'Dashboard' }),
  entry('combat.plan', 'combat', 'Target rejection and attack plan trace', 'capabilities combat', 'src/map/persistent_agent.cpp', 'Native PA', 'MISSING_DIAGNOSTIC', { provider: 'Native', gap: 'GAP_COMBAT_TRACE' }),
  entry('combat.anti_ks', 'combat', 'Future Anti-KS diagnostic seam', 'capabilities combat', 'docs/PROJECT_ROADMAP.md', 'future product decision', 'NOT_IMPLEMENTED_PRODUCT', { gap: 'GAP_FUTURE_ANTI_KS' }),
  entry('supply.state', 'supply', 'Task phase and last-error projection', 'player inspect <charId>', 'ops/ro-stack/dashboard.mjs:listAdminCharacters', 'Native PA through Admin read model', 'ALREADY_UNIFIED', { provider: 'Dashboard' }),
  entry('supply.purchase', 'supply', 'Merchant purchase and reserve detail', 'events recent <charId>', 'persistent_life_event; Native PA', 'Event Ledger and Native PA', 'EXISTS_SOURCE_ONLY', { provider: 'DB_READ_ONLY' }),
  entry('recovery.state', 'recovery', 'Quarantine state and last error', 'player inspect <charId>', 'ops/ro-stack/dashboard.mjs:listAdminCharacters', 'Native PA through Admin read model', 'ALREADY_UNIFIED', { provider: 'Dashboard' }),
  entry('recovery.eligibility', 'recovery', 'Read-only authoritative recovery admission', 'capabilities recovery', 'ops/ro-stack/dashboard/admin-quarantine-recovery.mjs', 'Dashboard Admin to Native', 'MISSING_DIAGNOSTIC', { gap: 'GAP_RECOVERY_ELIGIBILITY' }),
  entry('navigation.state', 'navigation', 'Map position and task phase', 'player inspect <charId>', 'ops/ro-stack/dashboard.mjs:listAdminCharacters', 'Native PA through Admin read model', 'ALREADY_UNIFIED', { provider: 'Dashboard' }),
  entry('navigation.stall', 'navigation', 'Stall reason and portal edge trace', 'events recent <charId>', 'persistent_life_event; Native PA', 'Event Ledger and Native PA', 'EXISTS_SOURCE_ONLY', { provider: 'DB_READ_ONLY' }),
  entry('quest.state', 'quest', 'Quest session and checkpoint diagnostics', 'capabilities quest', 'ops/ro-stack/dashboard.mjs; Native quest runtime', 'Native quest runtime', 'MISSING_DEVELOPER_ENTRYPOINT', { gap: 'GAP_QUEST_TRACE' }),
  entry('inventory.state', 'inventory', 'Inventory equipment weight and revision', 'capabilities inventory', 'Native inventory and Dashboard player state', 'rAthena', 'MISSING_DEVELOPER_ENTRYPOINT', { gap: 'GAP_INVENTORY_READ' }),
  entry('economy.zeny', 'economy', 'Zeny read model', 'player inspect <charId>', 'ops/ro-stack/dashboard.mjs:listAdminCharacters', 'rAthena through Admin read model', 'ALREADY_UNIFIED', { provider: 'Dashboard' }),
  entry('deployment.state', 'deployment', 'Current baseline, drift, lease and candidate', 'deployment state', '.local/ro-stack/production-deployment-state.json; production-deployment-lease/lease.json', 'Production governance records', 'ALREADY_UNIFIED', { provider: 'deployment tool' }),
  entry('deployment.receipt', 'deployment', 'Last accepted receipt identity', 'deployment receipt', '.local/ro-stack/production-deployment-state.json', 'Production deployment receipt', 'ALREADY_UNIFIED', { provider: 'deployment tool' }),
  entry('deployment.promote', 'deployment', 'GitHub-first promotion', 'capabilities deployment', 'ops/ro-stack/production-promotion-gate.mjs', 'promotion gate', 'EXISTS_SCRIPT_ONLY', { mode: 'STATE_CHANGING', provider: 'deployment tool', production: false }),
  entry('incident.procdump', 'incident', 'ProcDump attachment receipt', 'incident procdump', '.local/ro-stack/procdump-attachment-state.json', 'runtime sentinel', 'ALREADY_UNIFIED', { provider: 'incident tool' }),
  entry('incident.latest', 'incident', 'Latest runtime incident bundle', 'incident latest', '.local/ro-stack/runtime-incidents/*/incident.json', 'runtime incident observer', 'ALREADY_UNIFIED', { provider: 'incident tool' }),
  entry('config.diff', 'config', 'Canonical and deployed config hash/delta', 'config diff', 'ops/ro-stack/stack.config.psd1; Production stack.config.psd1', 'source and Production files', 'ALREADY_UNIFIED', { provider: 'deployment tool' }),
  entry('config.effective', 'config', 'Independent in-process effective Native config', 'capabilities config', 'ops/ro-stack/reconcile-active-runtime-config.mjs', 'Native runtime', 'MISSING_DIAGNOSTIC', { gap: 'GAP_EFFECTIVE_CONFIG' }),
  entry('web.freshness', 'web', 'Admin projection age and source freshness', 'player inspect <charId>', 'ops/ro-stack/dashboard.mjs:listAdminCharacters', 'Dashboard Admin read model', 'ALREADY_UNIFIED', { provider: 'Dashboard' }),
  entry('web.ui', 'web', 'Player UI acceptance', 'capabilities web', 'AGENTS.md §16', 'Browser observation', 'NOT_APPLICABLE', { browser: true }),
  entry('life.director', 'life', 'Life Director decision state', 'capabilities life', 'docs/character-life-social-simulation-roadmap.md', 'future Life Director', 'NOT_IMPLEMENTED_PRODUCT', { gap: 'GAP_FUTURE_LIFE' }),
  entry('life.social', 'life', 'Social Director relationship and interaction state', 'capabilities life', 'docs/character-life-social-simulation-roadmap.md', 'future Social Director', 'NOT_IMPLEMENTED_PRODUCT', { gap: 'GAP_FUTURE_SOCIAL' }),
  entry('life.memory', 'life', 'Mood memory and Daily Reflection state', 'capabilities life', 'docs/character-life-social-simulation-roadmap.md', 'future product', 'NOT_IMPLEMENTED_PRODUCT', { gap: 'GAP_FUTURE_MEMORY' }),
]);
