import { randomUUID } from 'node:crypto';
import { CombatPolicy, CommitType, InterruptPolicy, MissionStageType, QuestStatus, QuestStepType, RiskLevel } from './contracts.mjs';
import { defineJobQuestAdapter } from './job-adapter-contract.mjs';
import { questPreflightCheck, requestSupply } from './runtime.mjs';

export const CRUSADER_CAREER_JOURNEY_ID = 28004;
export const CRUSADER_JOB_ID = 14;
export const CRUSADER_SOURCE_JOB_ID = 1;
export const CRUSADER_ROSARY_ID = 2608;
export const CRUSADER_HOLY_WATER_ID = 523;

export const CrusaderPhase = Object.freeze({
  IDLE: 'IDLE', NAVIGATING: 'NAVIGATING', AT_GUILD: 'AT_GUILD', ACCEPTING: 'ACCEPTING',
  MATERIAL_REQUIRED: 'MATERIAL_REQUIRED', MATERIAL_SYNC: 'MATERIAL_SYNC', NO_KILL_READY: 'NO_KILL_READY',
  NO_KILL_STARTING: 'NO_KILL_STARTING', NO_KILL_ACTIVE: 'NO_KILL_ACTIVE', QUIZ: 'QUIZ', QUIZ_SYNC: 'QUIZ_SYNC',
  BATTLE_READY: 'BATTLE_READY', BATTLE_STARTING: 'BATTLE_STARTING', BATTLE_ACTIVE: 'BATTLE_ACTIVE',
  FINAL_READY: 'FINAL_READY', COMPLETED: 'COMPLETED',
});

export const CRUSADER_SOURCE = Object.freeze({
  file: 'npc/jobs/2-2/crusader.txt', renewalFile: 'npc/re/jobs/2-2/crusader.txt', loadedBy: 'npc/scripts_jobs.conf:29',
  revision: 'e985006171d2eb320ee512a653f4c83aea3d81b6',
  sha256: 'EF7A5B3BE140821455F724B2609B4AC1AAC94D34ABFC05E4C4143F450017E092',
  renewalSha256: 'DC7C42B0ED7652CA13ABA80C1ED1093976857287DBE6CFBEA0D360B997D7E90D',
  eligibility: Object.freeze({ baseJob: CRUSADER_SOURCE_JOB_ID, minimumJobLevel: 40, skillPoint: 0, lines: '50,119-135' }),
  guildMap: 'prt_cas', guildNpc: Object.freeze({ name: 'Senior Crusader', x: 251, y: 75, sourceLines: 're:12' }),
  enduranceNpc: Object.freeze({ name: 'Man in Anguish', x: 238, y: 94, sourceLines: 're:16' }),
  quizNpc: Object.freeze({ name: 'Gabriel Valentine', map: 'prt_church', x: 95, y: 127, sourceLines: '454-755' }),
  battleNpc: Object.freeze({ name: 'Patron Knight', x: 261, y: 101, sourceLines: 're:20' }),
  questIds: Object.freeze([3006, 3007, 3008, 3009, 3010, 3011, 3012, 3013, 3014, 3015]),
  variables: Object.freeze(['CRUS_Q', 'terminal_crusader_arrived', 'terminal_crusader_formal_started', 'terminal_crusader_material_branch', 'terminal_crusader_material_seed', 'terminal_crusader_shortcut', 'terminal_crusader_quiz_set', 'terminal_crusader_no_kill_started', 'terminal_crusader_no_kill_result', 'terminal_crusader_battle_started', 'terminal_crusader_battle_wave', 'terminal_crusader_battle_kills', 'terminal_crusader_battle_result', 'terminal_crusader_job_level']),
  finalJob: CRUSADER_JOB_ID, finalState: Object.freeze({ crusQ: 10, questId: 3015, sourceLines: '277-303,1278-1303' }),
});

const item = (itemId, amount, name) => Object.freeze({ itemId, amount, name });
export const CRUSADER_MATERIAL_BRANCHES = Object.freeze({
  1: Object.freeze({ questId: 3006, items: Object.freeze([item(957,10,'腐爛繃帶'),item(959,10,'腐臭鱗片'),item(1099,10,'破舊監獄服'),item(901,10,'亡者牙齒')]), sourceLines: '169-182,215-229' }),
  2: Object.freeze({ questId: 3007, items: Object.freeze([item(932,10,'亡者遺骨'),item(1043,10,'獸人指甲'),item(1098,10,'破舊肖像'),item(1094,10,'短蝙蝠毛')]), sourceLines: '183-188,231-244' }),
  3: Object.freeze({ questId: 3008, items: Object.freeze([item(958,10,'蛆皮'),item(930,10,'腐爛鱗片'),item(1041,10,'燈蛾翅膀'),item(1062,10,'傑勒比結晶')]), sourceLines: '189-196,246-260' }),
});
export const CRUSADER_SHORTCUT = Object.freeze({ items: Object.freeze([item(1004,1,'騎士團徽章'),item(1009,1,'神之手')]), consumes: true, sourceLines: '75-87,145-159' });
export const CRUSADER_EQUIPMENT_REQUIREMENTS = Object.freeze([
  Object.freeze({ itemId: CRUSADER_ROSARY_ID, name: '念珠', minimumAmount: 1, mustBeEquipped: true, slots: Object.freeze(['ACCESSORY_LEFT','ACCESSORY_RIGHT']), checkpoints: Object.freeze(['NO_KILL_ENTRY','BATTLE_ENTRY']), sourceLines: '364-368,405-413,892-901' }),
]);

const q = (id, prompt, choices, answer, sourceLines) => Object.freeze({ id, prompt, choices: Object.freeze(choices), answer, sourceLines });
export const CRUSADER_QUIZ_SETS = Object.freeze({
  1: Object.freeze([
    q('1-1','攻擊不死屬性時，哪種屬性最有效？',['無','地','不死','聖'],3,'535-537'),
    q('1-2','對不死屬性 Lv.2，聖屬性比火屬性多多少傷害？',['25%','50%','75%','100%'],0,'541-543'),
    q('1-3','邪骸浪人不會掉落哪個道具？',['修道士帽','天地樹葉子','白色藥草','護身符'],0,'547-549'),
    q('1-4','哪個不死系怪物的 HP 最高？',['腐屍','腐屍囚犯','惡靈','腐屍戰俘'],3,'553-556'),
    q('1-5','哪個怪物的體型與其他三者不同？',['惡靈','卡利斯格','德古拉伯爵','邪骸浪人'],2,'560-562'),
    q('1-6','哪張卡片可降低不死屬性攻擊傷害？',['獸人骷髏卡','獸人腐屍卡','腐屍卡','邪骸礦工卡'],1,'566-568'),
    q('1-7','殭屍與妖道生前是什麼關係？',['兄妹','同村青梅竹馬','異父母兄妹','陌生人'],1,'572-574'),
    q('1-8','哪個怪物不會主動攻擊？',['邪骸戰士','獸人骷髏','骷髏','邪骸礦工'],2,'578-580'),
    q('1-9','插入殭屍卡的盾牌名稱是？',['原子盾','護身符盾','催眠盾','荷梅洛斯盾'],1,'584-586'),
    q('1-10','哪個怪物不會掉落亡者遺物？',['殭屍','腐屍','木乃伊','邪骸戰士'],0,'590-592'),
  ]),
  2: Object.freeze([
    q('2-1','哪個怪物的屬性與其他三者不同？',['卡拉特小丑','風魔巫師','伊西拉','邪骸浪人'],2,'597-599'),
    q('2-2','哪把劍對惡魔系怪物有效？',['十字巨劍','神聖巨劍','詛咒巨劍','昏睡巨劍'],0,'603-605'),
    q('2-3','土人不會掉落哪個道具？',['鋁原石','黃金鐵鎚','劍錘','力量魔杖'],1,'609-611'),
    q('2-4','哪個惡魔系怪物 HP 最高？',['基爾瑟','木乃伊犬','土人','傀儡娃娃'],3,'615-617'),
    q('2-5','哪個惡魔系怪物體型不同？',['幽靈波利','白幽靈','小惡魔','巴風特之子'],0,'621-623'),
    q('2-6','哪種盾牌可降低惡魔系傷害？',['撒旦盾','地獄盾','護身符盾','優良盾'],1,'627-629'),
    q('2-7','對風魔巫師最有效的屬性是？',['水','地','火','風'],1,'633-635'),
    q('2-8','哪個怪物與其他惡魔系不同？',['鬼女','伊西拉','土人','白幽靈'],3,'639-641'),
    q('2-9','傀儡娃娃卡的效果是？',['暗屬性耐性30%','毒屬性耐性30%','念屬性耐性30%','無屬性耐性30%'],2,'645-647'),
    q('2-10','遇到惡魔系怪物時哪種做法有效？',['大喊退散','交易靈魂','以聖水祝福武器後攻擊','戴小惡魔帽'],2,'651-653'),
  ]),
  3: Object.freeze([
    q('3-1','學習惡魔剋星需要天使之護到幾級？',['1','2','3','4'],2,'658-660'),
    q('3-2','55 級且含加成 INT 30 時，治癒術 Lv.5 回復多少 HP？',['396','440','484','528'],1,'664-666'),
    q('3-3','天使之護 Lv.7 對不死系增加多少防禦？',['21','22','23','24'],0,'670-672'),
    q('3-4','哪把槍可攻擊念屬性的夢魘？',['長矛','長戟','鐮戟','風靈之矛'],3,'676-678'),
    q('3-5','學習緩毒術需要治癒術到幾級？',['1','2','3','4'],1,'682-684'),
    q('3-6','騎乘術熟練度 Lv.3 的攻速為一般速度多少？',['70%','80%','90%','100%'],1,'688-690'),
    q('3-7','關於惡魔剋星，哪項敘述錯誤？',['增加對不死系攻擊','只有服事能學','滿級增加30攻擊','被動技能'],1,'694-696'),
    q('3-8','治癒術 Lv.7 消耗多少 SP？',['30','31','33','35'],1,'700-702'),
    q('3-9','哪種狀態不能用緩毒術治癒？',['詛咒','沉默','混亂','黑暗'],0,'706-709'),
    q('3-10','哪項最能描述十字軍？',['準備結婚的人','準備聖戰的人','準備完成的人','準備藥水的人'],1,'713-715'),
  ]),
});

export const CRUSADER_NO_KILL = Object.freeze({ map: 'job_cru', start: Object.freeze({x:98,y:40}), destination: Object.freeze({x:98,y:105}), boundary: Object.freeze({map:'job_cru',minX:90,maxX:106,minY:34,maxY:108}), monsters: Object.freeze([{nameId:1020,name:'Mandragora'},{nameId:1118,name:'Flora'},{nameId:1277,name:'Greatest General'},{nameId:1005,name:'Familiar'},{nameId:1182,name:'Mushroom'}]), sourceLines: '377-390,983-1210; re:28-35' });
export const CRUSADER_BATTLE_WAVES = Object.freeze([
  Object.freeze({wave:1,total:6,monsters:Object.freeze([{nameId:1015,name:'Zombie',amount:6}]),sourceLines:'1261-1268'}),
  Object.freeze({wave:2,total:3,monsters:Object.freeze([{nameId:1028,name:'Soldier Skeleton',amount:3}]),sourceLines:'1270-1274'}),
  Object.freeze({wave:3,total:2,monsters:Object.freeze([{nameId:1016,name:'Archer Skeleton',amount:1},{nameId:1041,name:'Mummy',amount:1}]),sourceLines:'1276-1279'}),
]);
export const CRUSADER_REWARD = Object.freeze({ itemId: 504, name: '白色藥水', normalAmount: 6, jobLevel50Amount: 12, sourceLines: '288-296' });

const questState = (authority,id) => Number(authority?.questStates?.[id] ?? -1);
const evolve = (state,patch) => ({...state,...patch,revision:Number(state.revision)+1,updatedAt:new Date().toISOString()});
const step = (id,type,interruptPolicy) => ({id,type,interruptPolicy,missionStage:{type:type===QuestStepType.TRIAL?MissionStageType.TRIAL:MissionStageType.DIALOG}});
const checkpoint = (state,stepId,data) => { const completedSteps=state.completedSteps.includes(stepId)?[...state.completedSteps]:[...state.completedSteps,stepId]; return {completedSteps,checkpoint:{stepId,completedSteps,data:structuredClone(data??null),createdAt:new Date().toISOString()}}; };
const publicQuestions = (questions) => questions.map(({id,prompt,choices,sourceLines})=>({id,prompt,choices:[...choices],sourceLines}));
export function crusaderServerCommand(action,values=[]){return{name:'terminal_crusader_sync',arguments:[action,...values.map(String)]};}
export function crusaderEligibility(authority){const failures=[]; if(Number(authority?.currentJob)!==CRUSADER_SOURCE_JOB_ID)failures.push('JOB_MUST_BE_SWORDMAN'); if(Number(authority?.jobLevel)<40)failures.push('JOB_LEVEL_40_REQUIRED'); if(Number(authority?.skillPoint)!==0)failures.push('UNUSED_FIRST_JOB_SKILL_POINTS'); if(Number(authority?.currentJob)===CRUSADER_JOB_ID||questState(authority,3015)===2)failures.push('CRUSADER_QUEST_ALREADY_COMPLETED'); return{eligible:failures.length===0,failures};}
export function crusaderEquipmentStatus(authority){const equipped=Number(authority?.equippedItems?.[CRUSADER_ROSARY_ID]??0);return{ready:equipped>=1,itemId:CRUSADER_ROSARY_ID,name:'念珠',equipped,required:1,message:'需要裝備念珠才能開始試煉。'};}
export function initializeCrusaderState(state){if(state.crusader)return state;return{...state,crusader:{phase:CrusaderPhase.IDLE,formalQuestStarted:false,sourceState:null,materialBranch:null,shortcutUsed:false,quiz:{setId:null,answers:[],score:null,attempts:0,passed:false},noKill:{startedAt:null},battle:{wave:0,kills:0,startedAt:null},results:{materials:false,noKill:false,quiz:false,battle:false,jobChange:false}}};}
export function selectCrusaderCareer(state,target){state=initializeCrusaderState(state);if(String(target??'').toUpperCase()!=='CRUSADER')throw new Error('CAREER_TARGET_INVALID');return evolve(state,{careerTarget:'CRUSADER'});}
function objective(state,phase,id,type,interruptPolicy,missionStage,currentObjective,crusaderPatch={},rootPatch={}){return evolve(state,{...rootPatch,questStatus:rootPatch.questStatus??QuestStatus.RUNNING,currentStep:step(id,type,interruptPolicy),currentObjective,objectiveId:id,objectiveGeneration:Number(state.objectiveGeneration??0)+1,agentLease:null,interruptPolicy,missionStage,crusader:{...state.crusader,...crusaderPatch,phase}});}
function serverObjective(state,phase,action,title,values=[],crusaderPatch={},rootPatch={}){return objective(state,phase,`crusader.server.${action}`,QuestStepType.OBJECTIVE,InterruptPolicy.LOCKED,{type:MissionStageType.DIALOG,title,status:'SERVER_PENDING'},{type:'SERVER_COMMAND',action,serverCommand:crusaderServerCommand(action,values),preserveNavigationHold:true},crusaderPatch,rootPatch);}
function materialStatus(authority,branchId){const branch=CRUSADER_MATERIAL_BRANCHES[branchId];const missingItems=(branch?.items??[]).map(e=>({...e,current:Number(authority?.items?.[e.itemId]??0),missing:Math.max(0,e.amount-Number(authority?.items?.[e.itemId]??0))})).filter(e=>e.missing>0);return{ready:Boolean(branch)&&missingItems.length===0,missingItems};}
function validAnswers(answers,size){return Array.isArray(answers)&&answers.length===size&&answers.every(a=>Number.isInteger(Number(a))&&Number(a)>=0&&Number(a)<=3);}
function quizScore(set,answers){return set.reduce((score,entry,index)=>score+(Number(answers[index])===entry.answer?10:0),0);}
export function applyCrusaderAction(state,action,payload,authority,{preflight=null}={}){
  state=initializeCrusaderState(state);const phase=state.crusader.phase;
  if(action==='NAVIGATE_GUILD'){if(state.careerTarget!=='CRUSADER')throw new Error('CRUSADER_CAREER_TARGET_REQUIRED');const e=crusaderEligibility(authority);if(!e.eligible)throw new Error(e.failures[0]);return objective(state,CrusaderPhase.NAVIGATING,'crusader.navigate_guild',QuestStepType.OBJECTIVE,InterruptPolicy.DEFERRED,{type:MissionStageType.NAVIGATION,title:'前往普隆德拉十字軍總部',currentMap:authority?.map??null,nextMap:'prt_cas',npc:'Senior Crusader',formalQuestStarted:false},{type:'SERVER_COMMAND',action:'navigate_guild',serverCommand:crusaderServerCommand('navigate_guild'),preserveNavigationHold:true},{},{questId:CRUSADER_CAREER_JOURNEY_ID,questSessionId:state.questSessionId??randomUUID(),completedSteps:[],checkpoint:null});}
  if(action==='ACCEPT_QUEST'){if(phase!==CrusaderPhase.AT_GUILD)throw new Error('CRUSADER_GUILD_NOT_REACHED');const e=crusaderEligibility(authority);if(!e.eligible)throw new Error(e.failures[0]);if(authority?.map!=='prt_cas'&&Number(authority?.variables?.terminal_crusader_arrived)!==1)throw new Error('CRUSADER_GUILD_NOT_REACHED');return serverObjective(state,CrusaderPhase.ACCEPTING,'accept','Senior Crusader 正式受理十字軍轉職考試');}
  if(action==='SUBMIT_MATERIALS'){if(phase!==CrusaderPhase.MATERIAL_REQUIRED)throw new Error('MATERIAL_STAGE_NOT_ACTIVE');const status=materialStatus(authority,state.crusader.materialBranch?.id);if(!status.ready)return evolve(state,{missionStage:{...state.missionStage,type:MissionStageType.RESULT,status:'INSUFFICIENT',missingItems:status.missingItems}});return serverObjective(state,CrusaderPhase.MATERIAL_SYNC,'submit_materials','Senior Crusader 驗證並收取材料');}
  if(action==='START_NO_KILL'){if(phase!==CrusaderPhase.NO_KILL_READY)throw new Error('NO_KILL_NOT_READY');const equipment=crusaderEquipmentStatus(authority);if(!equipment.ready)return evolve(state,{missionStage:{...state.missionStage,type:MissionStageType.RESULT,status:'EQUIPMENT_REQUIRED',equipmentRequirement:equipment}});if(!['PASS','WARNING'].includes(preflight?.status))throw new Error('NO_KILL_PREFLIGHT_BLOCKED');return objective(state,CrusaderPhase.NO_KILL_STARTING,'crusader.no_kill_trial',QuestStepType.TRIAL,InterruptPolicy.LOCKED,{type:MissionStageType.TRIAL,title:'十字軍禁殺走廊',status:'STARTING',rule:'NO_KILL',destination:'走廊另一端',equipmentRequirement:equipment},{type:'NO_KILL_ROUTE',action:'no_kill_start',serverCommand:crusaderServerCommand('no_kill_start'),completionServerCommand:crusaderServerCommand('no_kill_finish'),map:CRUSADER_NO_KILL.map,x:CRUSADER_NO_KILL.destination.x,y:CRUSADER_NO_KILL.destination.y,range:0,directStepMovement:true,completionQuestId:3011,preserveNavigationHold:true,trialBoundary:CRUSADER_NO_KILL.boundary},{noKill:{startedAt:new Date().toISOString()}},{questStatus:QuestStatus.TRIAL_ACTIVE,activeTrial:{id:'crusader.no_kill',startedAt:new Date().toISOString()},trialInventoryLock:true,previousCombatPolicy:structuredClone(state.combatPolicy),combatPolicy:{mode:CombatPolicy.NO_ATTACK,targets:[],avoidHostiles:true,avoidHostilesRange:4}});}
  if(action==='SUBMIT_QUIZ'){if(phase!==CrusaderPhase.QUIZ)throw new Error('QUIZ_NOT_ACTIVE');const setId=Number(state.crusader.quiz.setId);const set=CRUSADER_QUIZ_SETS[setId];const answers=payload?.answers?.map(Number);if(!set||!validAnswers(answers,set.length))throw new Error('QUIZ_ANSWERS_INVALID');const score=quizScore(set,answers);const attempts=Number(state.crusader.quiz.attempts)+1;const passed=score>=90||(attempts>1&&score>=80);const quiz={setId,answers,score,attempts,passed};return serverObjective(state,CrusaderPhase.QUIZ_SYNC,'quiz_submit','Gabriel Valentine 驗證測驗結果',[setId,...answers],{quiz});}
  if(action==='START_BATTLE'){if(phase!==CrusaderPhase.BATTLE_READY)throw new Error('BATTLE_NOT_READY');const equipment=crusaderEquipmentStatus(authority);if(!equipment.ready)return evolve(state,{missionStage:{...state.missionStage,type:MissionStageType.RESULT,status:'EQUIPMENT_REQUIRED',equipmentRequirement:equipment}});if(Number(authority?.items?.[CRUSADER_HOLY_WATER_ID]??0)<1)throw new Error('HOLY_WATER_REQUIRED');if(!['PASS','WARNING'].includes(preflight?.status))throw new Error('BATTLE_PREFLIGHT_BLOCKED');return objective(state,CrusaderPhase.BATTLE_STARTING,'crusader.undead_battle',QuestStepType.TRIAL,InterruptPolicy.LOCKED,{type:MissionStageType.TRIAL,title:'十字軍不死系限時戰鬥',status:'STARTING',rule:'TIMED_WAVE_BATTLE',timeoutSeconds:240,waves:CRUSADER_BATTLE_WAVES,equipmentRequirement:equipment},{type:'SERVER_COMMAND',action:'battle_start',after:'COMBAT_HOLD',serverCommand:crusaderServerCommand('battle_start'),completionQuestId:3015,preserveNavigationHold:true},{battle:{wave:1,kills:0,startedAt:new Date().toISOString()}},{questStatus:QuestStatus.TRIAL_ACTIVE,activeTrial:{id:'crusader.undead_battle',startedAt:new Date().toISOString()},trialInventoryLock:true,previousCombatPolicy:structuredClone(state.combatPolicy),combatPolicy:{mode:CombatPolicy.NORMAL,targets:[]}});}
  throw new Error('CRUSADER_ACTION_INVALID');
}
function sourceSnapshot(authority){return{q:Number(authority?.variables?.CRUS_Q??0),branch:Number(authority?.variables?.terminal_crusader_material_branch??0),shortcut:Number(authority?.variables?.terminal_crusader_shortcut??0),quizSet:Number(authority?.variables?.terminal_crusader_quiz_set??0),noKillStarted:Number(authority?.variables?.terminal_crusader_no_kill_started??0),noKillResult:Number(authority?.variables?.terminal_crusader_no_kill_result??0),battleStarted:Number(authority?.variables?.terminal_crusader_battle_started??0),battleWave:Number(authority?.variables?.terminal_crusader_battle_wave??0),battleKills:Number(authority?.variables?.terminal_crusader_battle_kills??0),battleResult:Number(authority?.variables?.terminal_crusader_battle_result??0),jobLevel:Number(authority?.variables?.terminal_crusader_job_level??authority?.jobLevel??0),quests:authority?.questStates??{}};}
function releaseTrial(state,patch){return{...patch,currentObjective:null,agentLease:null,activeTrial:null,trialInventoryLock:false,interruptPolicy:InterruptPolicy.SAFE,combatPolicy:state.previousCombatPolicy??{mode:CombatPolicy.NORMAL,targets:[]},previousCombatPolicy:null};}
export function reconcileCrusaderState(state,authority){state=initializeCrusaderState(state);const phase=state.crusader.phase;const source=sourceSnapshot(authority);
  if([CrusaderPhase.NO_KILL_STARTING,CrusaderPhase.NO_KILL_ACTIVE].includes(phase)&&(state.questStatus===QuestStatus.TRIAL_FAILED||source.noKillResult<0||(source.q===5&&source.noKillStarted>0&&authority?.map&&authority.map!=='job_cru')))return evolve(state,releaseTrial(state,{questStatus:QuestStatus.READY,missionStage:{type:MissionStageType.RESULT,title:'禁殺走廊中斷',status:'READY_TO_RETRY',checkpoint:state.checkpoint},crusader:{...state.crusader,phase:CrusaderPhase.NO_KILL_READY,sourceState:source}}));
  if([CrusaderPhase.BATTLE_STARTING,CrusaderPhase.BATTLE_ACTIVE].includes(phase)&&(state.questStatus===QuestStatus.TRIAL_FAILED||source.battleResult<0))return evolve(state,releaseTrial(state,{questStatus:QuestStatus.READY,missionStage:{type:MissionStageType.RESULT,title:'不死系戰鬥中斷',status:'READY_TO_RETRY',checkpoint:state.checkpoint},crusader:{...state.crusader,phase:CrusaderPhase.BATTLE_READY,sourceState:source}}));
  if(phase===CrusaderPhase.NAVIGATING&&(authority?.map==='prt_cas'||Number(authority?.variables?.terminal_crusader_arrived)===1))return evolve(state,{questStatus:QuestStatus.READY,currentObjective:null,agentLease:null,missionStage:{type:MissionStageType.DIALOG,title:'Senior Crusader',status:'READY',actionLabel:'接受十字軍轉職考試'},crusader:{...state.crusader,phase:CrusaderPhase.AT_GUILD,sourceState:source}});
  if(phase===CrusaderPhase.ACCEPTING&&[1,2,3].includes(source.q)&&CRUSADER_MATERIAL_BRANCHES[source.q]){const branch=CRUSADER_MATERIAL_BRANCHES[source.q];return evolve(state,{formalQuestStarted:true,questId:branch.questId,questStatus:QuestStatus.READY,currentObjective:null,agentLease:null,currentStep:step('crusader.materials',QuestStepType.REQUIREMENT,InterruptPolicy.SAFE),interruptPolicy:InterruptPolicy.SAFE,missionStage:{type:MissionStageType.RESULT,title:'十字軍材料試煉',status:'REQUIRED',branch:source.q,items:branch.items,sourceLines:branch.sourceLines},crusader:{...state.crusader,phase:CrusaderPhase.MATERIAL_REQUIRED,formalQuestStarted:true,materialBranch:{id:source.q,...branch},sourceState:source}});}
  if(phase===CrusaderPhase.ACCEPTING&&source.q===4&&questState(authority,3009)>=0){const done=checkpoint(state,'crusader.materials',{shortcut:true,consumed:[1004,1009]});return evolve(state,{...done,formalQuestStarted:true,questId:3009,questStatus:QuestStatus.READY,currentObjective:null,agentLease:null,currentStep:step('crusader.no_kill_trial',QuestStepType.TRIAL,InterruptPolicy.SAFE),interruptPolicy:InterruptPolicy.SAFE,missionStage:{type:MissionStageType.TRIAL,title:'十字軍禁殺走廊',status:'READY',rule:'NO_KILL',equipmentRequirement:crusaderEquipmentStatus(authority),actionLabel:'檢查裝備與補給後開始'},crusader:{...state.crusader,phase:CrusaderPhase.NO_KILL_READY,formalQuestStarted:true,shortcutUsed:true,sourceState:source,results:{...state.crusader.results,materials:true}}});}
  if(phase===CrusaderPhase.MATERIAL_SYNC&&source.q===4&&questState(authority,3009)>=0){const done=checkpoint(state,'crusader.materials',{branch:state.crusader.materialBranch?.id});return evolve(state,{...done,questId:3009,questStatus:QuestStatus.READY,currentObjective:null,agentLease:null,currentStep:step('crusader.no_kill_trial',QuestStepType.TRIAL,InterruptPolicy.SAFE),interruptPolicy:InterruptPolicy.SAFE,missionStage:{type:MissionStageType.TRIAL,title:'十字軍禁殺走廊',status:'READY',rule:'NO_KILL',equipmentRequirement:crusaderEquipmentStatus(authority),actionLabel:'檢查裝備與補給後開始'},crusader:{...state.crusader,phase:CrusaderPhase.NO_KILL_READY,sourceState:source,results:{...state.crusader.results,materials:true}}});}
  if(phase===CrusaderPhase.NO_KILL_STARTING&&source.q===5&&questState(authority,3010)>=0)return evolve(state,{questStatus:QuestStatus.TRIAL_ACTIVE,missionStage:{...state.missionStage,status:'ACTIVE',currentMap:authority?.map,destination:'走廊另一端'},crusader:{...state.crusader,phase:CrusaderPhase.NO_KILL_ACTIVE,sourceState:source}});
  if(phase===CrusaderPhase.NO_KILL_ACTIVE&&source.q===6&&questState(authority,3011)>=0){const done=checkpoint(state,'crusader.no_kill_trial',{killed:0,destination:CRUSADER_NO_KILL.destination});const set=CRUSADER_QUIZ_SETS[source.quizSet];return evolve(state,releaseTrial(state,{...done,questId:3011,questStatus:QuestStatus.RUNNING,currentStep:step('crusader.quiz',QuestStepType.CHOICE,InterruptPolicy.SAFE),missionStage:{type:MissionStageType.QUIZ,title:'Gabriel Valentine 十字軍知識測驗',status:'ACTIVE',setId:source.quizSet,requiredFirst:90,requiredRetry:80,questions:publicQuestions(set??[])},crusader:{...state.crusader,phase:CrusaderPhase.QUIZ,sourceState:source,quiz:{...state.crusader.quiz,setId:source.quizSet},results:{...state.crusader.results,noKill:true}}}));}
  if(phase===CrusaderPhase.QUIZ_SYNC&&source.q===7&&questState(authority,3012)>=0)return evolve(state,{questId:3012,questStatus:QuestStatus.RUNNING,currentObjective:null,agentLease:null,interruptPolicy:InterruptPolicy.SAFE,missionStage:{type:MissionStageType.QUIZ,title:'Gabriel Valentine 十字軍知識測驗',status:'FAILED',score:state.crusader.quiz.score,required:80,setId:source.quizSet,questions:publicQuestions(CRUSADER_QUIZ_SETS[source.quizSet]??[])},crusader:{...state.crusader,phase:CrusaderPhase.QUIZ,sourceState:source}});
  if(phase===CrusaderPhase.QUIZ_SYNC&&source.q===8&&questState(authority,3013)>=0){const done=checkpoint(state,'crusader.quiz',{setId:source.quizSet,score:state.crusader.quiz.score,attempts:state.crusader.quiz.attempts});return evolve(state,{...done,questId:3013,questStatus:QuestStatus.READY,currentObjective:null,agentLease:null,currentStep:step('crusader.undead_battle',QuestStepType.TRIAL,InterruptPolicy.SAFE),interruptPolicy:InterruptPolicy.SAFE,missionStage:{type:MissionStageType.TRIAL,title:'十字軍不死系限時戰鬥',status:'READY',timeoutSeconds:240,waves:CRUSADER_BATTLE_WAVES,holyWater:{itemId:523,required:1,current:Number(authority?.items?.[523]??0)},equipmentRequirement:crusaderEquipmentStatus(authority),actionLabel:'檢查裝備、聖水與補給後開始'},crusader:{...state.crusader,phase:CrusaderPhase.BATTLE_READY,sourceState:source,results:{...state.crusader.results,quiz:true}}});}
  if(phase===CrusaderPhase.BATTLE_STARTING&&source.q===9&&source.battleStarted>0)return evolve(state,{questStatus:QuestStatus.TRIAL_ACTIVE,missionStage:{type:MissionStageType.TRIAL,title:'十字軍不死系限時戰鬥',status:'ACTIVE',rule:'TIMED_WAVE_BATTLE',timeoutSeconds:240,wave:source.battleWave,kills:source.battleKills,total:CRUSADER_BATTLE_WAVES[source.battleWave-1]?.total??0},crusader:{...state.crusader,phase:CrusaderPhase.BATTLE_ACTIVE,sourceState:source,battle:{wave:source.battleWave,kills:source.battleKills,startedAt:state.crusader.battle.startedAt}}});
  if(phase===CrusaderPhase.BATTLE_ACTIVE&&source.q===10&&source.battleResult===1&&questState(authority,3015)>=0){const done=checkpoint(state,'crusader.undead_battle',{waves:3,kills:11,timeoutSeconds:240});return evolve(state,releaseTrial(state,{...done,questId:3015,questStatus:QuestStatus.READY,currentStep:step('crusader.final_commit',QuestStepType.COMMIT,InterruptPolicy.LOCKED),interruptPolicy:InterruptPolicy.LOCKED,missionStage:{type:MissionStageType.RESULT,title:'Senior Crusader 最終認可',status:'READY_TO_COMMIT',finalNpc:'Senior Crusader',reward:{...CRUSADER_REWARD,amount:source.jobLevel===50?12:6}},crusader:{...state.crusader,phase:CrusaderPhase.FINAL_READY,sourceState:source,results:{...state.crusader.results,battle:true}}}));}
  if(phase===CrusaderPhase.BATTLE_ACTIVE&&(source.battleWave!==state.crusader.battle.wave||source.battleKills!==state.crusader.battle.kills))return evolve(state,{missionStage:{...state.missionStage,wave:source.battleWave,kills:source.battleKills,total:CRUSADER_BATTLE_WAVES[source.battleWave-1]?.total??0},crusader:{...state.crusader,sourceState:source,battle:{...state.crusader.battle,wave:source.battleWave,kills:source.battleKills}}});
  if(phase!==CrusaderPhase.COMPLETED&&Number(authority?.currentJob)===CRUSADER_JOB_ID&&questState(authority,3015)===2){const sourceJobLevel=source.jobLevel>1?source.jobLevel:Number(state.crusader.sourceState?.jobLevel??0);const amount=sourceJobLevel===50?12:6;const done=checkpoint(state,'crusader.final_commit',{classId:CRUSADER_JOB_ID,rewardItemId:504,rewardAmount:amount});return evolve(state,{...done,careerTarget:null,formalQuestStarted:false,questId:3015,questStatus:QuestStatus.COMPLETED,currentStep:null,currentObjective:null,objectiveId:null,agentLease:null,activeTrial:null,trialInventoryLock:false,supplyPending:false,originalObjective:null,temporaryObjective:null,interruptPolicy:InterruptPolicy.SAFE,combatPolicy:state.previousCombatPolicy??{mode:CombatPolicy.NORMAL,targets:[]},previousCombatPolicy:null,missionStage:{type:MissionStageType.RESULT,title:'正式轉職完成',status:'COMPLETED',job:'十字軍'},crusader:{...state.crusader,phase:CrusaderPhase.COMPLETED,sourceState:{...source,jobLevel:sourceJobLevel},results:{...state.crusader.results,jobChange:true}}});}
  return state;
}
function trialPreflight(authority){return questPreflightCheck({character:{hp:Number(authority?.hp??0),maxHp:Number(authority?.maxHp??1),sp:Number(authority?.sp??0),maxSp:Number(authority?.maxSp??0)},recoveryItems:[{itemId:501,amount:Number(authority?.items?.[501]??0),hpRecovery:1,spRecovery:0},{itemId:504,amount:Number(authority?.items?.[504]??0),hpRecovery:1,spRecovery:0}],riskLevel:RiskLevel.TRIAL,requirement:{minimumEntryHp:1,reservedHpRecovery:30}});}
function prepareCrusaderAction({state,action,payload,authority}){if(!['START_NO_KILL','START_BATTLE'].includes(action))return applyCrusaderAction(state,action,payload,authority);const equipment=crusaderEquipmentStatus(authority);if(!equipment.ready)return applyCrusaderAction(state,action,payload,authority,{preflight:{status:'PASS'}});if(action==='START_BATTLE'&&Number(authority?.items?.[523]??0)<1){const pending={...state,currentStep:step('crusader.undead_battle',QuestStepType.TRIAL,InterruptPolicy.SAFE)};return requestSupply(pending,{reservation:null,temporaryObjective:{type:'SUPPLY',reason:'CRUSADER_HOLY_WATER_REQUIRED',requirements:{items:[{itemId:523,minimumAmount:1}]}}});}const preflight=trialPreflight(authority);if(['PASS','WARNING'].includes(preflight.status))return applyCrusaderAction(state,action,payload,authority,{preflight});const pending=applyCrusaderAction(state,action,payload,authority,{preflight:{...preflight,status:'PASS'}});return requestSupply({...pending,activeTrial:null,trialInventoryLock:false,interruptPolicy:InterruptPolicy.SAFE},{reservation:preflight.reservation,temporaryObjective:{type:'SUPPLY',reason:action==='START_BATTLE'?'CRUSADER_BATTLE_RESERVE':'CRUSADER_NO_KILL_RESERVE',requirements:{items:[{itemId:501,minimumAmount:10}]}}});}
const requiredItems=new Map([[501,10],[504,0],[523,1],[2608,1],[1004,1],[1009,1]]);for(const branch of Object.values(CRUSADER_MATERIAL_BRANCHES))for(const entry of branch.items)requiredItems.set(entry.itemId,entry.amount);
export const CRUSADER_JOB_ADAPTER=defineJobQuestAdapter({id:'CRUSADER',displayName:'十字軍',version:1,jobId:CRUSADER_JOB_ID,eligibility:{sourceJobId:CRUSADER_SOURCE_JOB_ID,minimumJobLevel:40,skillPoint:0,evaluate:crusaderEligibility},questStateMapping:CRUSADER_SOURCE,steps:Object.freeze(['navigate_guild','accept','materials','no_kill_trial','quiz','undead_battle','final_commit']),quizDefinitions:Object.freeze(Object.values(CRUSADER_QUIZ_SETS)),trialDefinitions:Object.freeze([{id:'no_kill',kind:'NO_KILL_ROUTE',combatPolicy:CombatPolicy.NO_ATTACK,movementPolicy:'AVOID_HOSTILES',...CRUSADER_NO_KILL},{id:'undead_battle',kind:'TIMED_WAVE_BATTLE',combatPolicy:CombatPolicy.NORMAL,timeoutSeconds:240,waves:CRUSADER_BATTLE_WAVES,sourceLines:'1223-1410'}]),routeEvents:{},requiredItems:Object.freeze([...requiredItems].map(([itemId,minimumAmount])=>Object.freeze({itemId,minimumAmount,purpose:itemId===2608?'EQUIPMENT_GATE':itemId===523?'BATTLE_ENTRY':itemId===504?'REWARD_AUDIT':itemId===501?'TRIAL_PREFLIGHT':itemId===1004||itemId===1009?'SHORTCUT':'ITEM_GATE'}))),equipmentRequirements:CRUSADER_EQUIPMENT_REQUIREMENTS,checkpointRules:Object.freeze({materialFailure:'REMAIN_ITEM_OBJECTIVE',noKillFailure:'NO_KILL_READY',quizFailure:'RETRY_QUIZ',battleFailure:'BATTLE_READY',death:'CURRENT_TRIAL_READY'}),initializeState:initializeCrusaderState,selectCareerTarget:selectCrusaderCareer,applyAction:applyCrusaderAction,prepareAction:prepareCrusaderAction,reconcileState:reconcileCrusaderState,publicState:state=>structuredClone(state.crusader??null),publicStatus:state=>{const phase=state.crusader?.phase??CrusaderPhase.IDLE;return{phase,active:![CrusaderPhase.IDLE,CrusaderPhase.COMPLETED].includes(phase),formalQuestStarted:state.crusader?.formalQuestStarted===true};},finalCommit:{commitType:CommitType.JOB_CHANGE,payload:Object.freeze({adapterId:'CRUSADER',targetJobId:CRUSADER_JOB_ID}),completionQuestId:3015,command:crusaderServerCommand('commit'),validate:({authority,payload})=>{if(payload?.adapterId!=='CRUSADER'||Number(payload?.targetJobId)!==CRUSADER_JOB_ID)throw new Error('JOB_ADAPTER_COMMIT_PAYLOAD_INVALID');const e=crusaderEligibility(authority);if(!e.eligible)throw new Error(e.failures[0]);if(Number(authority?.variables?.CRUS_Q??0)!==10||Number(authority?.variables?.terminal_crusader_battle_result??0)!==1||questState(authority,3015)<0)throw new Error('CRUSADER_FINAL_STATE_INVALID');},isComplete:authority=>Number(authority?.currentJob)===CRUSADER_JOB_ID&&questState(authority,3015)===2,result:authority=>({verified:true,source:'rAthena/MariaDB',currentJob:Number(authority.currentJob),jobLevel:Number(authority.jobLevel),questId:3015,questState:questState(authority,3015),reward:{itemId:504,amount:Number(authority?.items?.[504]??0)}})}});
